-- ════════════════════════════════════════════════
-- Migration 0011 — teste_oportunidades (staging p/ relatório eGO CRM)
-- ════════════════════════════════════════════════
-- Fase 2 (relatórios), 2ª acção. Existe uma tabela `oportunidades` real em
-- produção (~90 colunas — confirmado 2026-07-27, nunca tinha sido
-- documentada em docs/database-schema.md nem referenciada em código deste
-- repo). `teste_oportunidades` clona os nomes de coluna dessa tabela, mas
-- TODAS `text` (+ `extra jsonb` p/ o que não corresponder a nenhuma) —
-- staging p/ inspeccionar valores crus do relatório antes de decidir
-- tipos/transformações, mesmo padrão de `teste_imoveis` (migrations
-- 0009/0010). NÃO tocar em `oportunidades` (produção) enquanto for teste.

create table teste_oportunidades (
  id                        uuid primary key default uuid_generate_v4(),
  oportunidade_ref          text,
  tipo_oportunidade         text,
  data_criacao_raw          text,
  data_criacao_iso          text,
  cliente_nome              text,
  cliente_telefone          text,
  cliente_email             text,
  url                       text,
  origem_lista              text,
  titulo_imovel             text,
  backup_em                 text,
  atualizado_em             text,
  etapa_atual               text,
  etapa_dias                text,
  preferencia_imovel        text,
  oportunidade_estado       text,
  ultima_consulta_em        text,
  responsavel               text,
  xlsx_ref_im               text,
  xlsx_angariador           text,
  xlsx_valor                text,
  xlsx_comm_ag              text,
  xlsx_comm_ang             text,
  xlsx_comm_vend            text,
  xlsx_margem               text,
  xlsx_origem               text,
  xlsx_estado_prop          text,
  xlsx_data_fecho           text,
  xlsx_data_prop            text,
  xlsx_exclusivo            text,
  xlsx_atualizado_em        text,
  ego_data_criacao          text,
  ego_editado_em            text,
  tipo_pedido               text,
  origem                    text,
  sub_origem                text,
  portal                    text,
  imovel_preco              text,
  proposta                  text,
  diferenca                 text,
  data_proposta             text,
  estado_proposta           text,
  etapa_proposta            text,
  probabilidade             text,
  agencia                   text,
  agencia_email             text,
  agencia_telefone          text,
  etapas_cpcv               text,
  etapas_escrituras         text,
  checklist_financiamento   text,
  checklist_cpcv            text,
  checklist_escrituras      text,
  imovel_proprietario       text,
  imovel_ref                text,
  imovel_natureza           text,
  imovel_distrito           text,
  imovel_concelho           text,
  imovel_freguesia          text,
  imovel_venda              text,
  imovel_arrendamento       text,
  estado_fechado_em         text,
  data_escritura            text,
  valor_negocio             text,
  equipa_responsavel        text,
  visita_imovel_ref         text,
  visita_anulada            text,
  visita_interessado        text,
  visita_data               text,
  visita_imovel_proprietario text,
  visita_cliente            text,
  visita_pontos_positivos   text,
  visita_pontos_negativos   text,
  visita_sobre_negocio      text,
  visita_observacoes        text,
  visita_responsavel        text,
  imovel2_ref               text,
  imovel2_distrito          text,
  imovel2_concelho          text,
  imovel2_freguesia         text,
  imovel2_venda             text,
  imovel2_arrendamento      text,
  pref_tipologia            text,
  pref_orcamento_max        text,
  pref_zona                 text,
  pref_extraido_em          text,
  pref_outros               text,
  ponto_situacao            text,
  ponto_situacao_alterado_em text,
  motivo_transacao          text,
  pref_natureza             text,
  pref_negocio              text,
  pref_preco_min            text,
  pref_disponibilidade      text,
  visita_ref_ego            text,
  extra                     jsonb default '{}'::jsonb,  -- colunas do relatório sem correspondência em `oportunidades`
  criado_em                 timestamptz default now()
);

alter table teste_oportunidades enable row level security;
create policy auth_full_access on teste_oportunidades for all to authenticated using (true) with check (true);
